/**
 * Run-level action buttons.
 *
 * A run is an immutable execution record. Re-processing a document is
 * a document-level action — see "Re-Index Document" on the Document
 * page. This component only exposes actions whose scope is THIS run:
 *
 *   * **Pause / Cancel** — operator workflow control while the run is
 *     in-flight.
 *   * **Run enrichment / Refresh enrichment** — active-run only.
 *     Label flips based on whether enrichment artifacts already
 *     exist on the active run.
 *   * **Clean Up Run** — hard-remove every record this non-active
 *     terminal run owns (artifacts on disk + registry, run snapshot,
 *     validation history). Eligibility is server-side: the button
 *     calls ``POST /ingestion-runs/{id}/clean-up`` which returns a
 *     structured ``{cleaned, reason, message}`` result — a refusal
 *     (active run / processing / only run) is NOT an HTTP error,
 *     and we render the server's ``message`` verbatim. The only-run
 *     case stays gated by ``isOnlyRun`` with a hint pointing at
 *     Remove Knowledge.
 *
 * Every action gate comes from server-side capability flags on the
 * ``DocumentRunSummary`` (``isActive``, ``isOnlyRun``,
 * ``canDeleteRun``, ``canRefreshEnrichment``, ``canRunEnrichment``).
 * The frontend MUST NOT recompute these locally — the server is the
 * source of truth, including for the active-run identity.
 */

import { useCallback, useState } from "react";
import { ApiError, type RunControlResult } from "@/lib/api/client";
import { useClient } from "@/lib/hooks/useClient";
import {
  CANCELLABLE_STATUSES,
  PAUSABLE_STATUSES,
  RUN_STATUS,
} from "@/lib/constants/runStatus";
import { hideLegacyRefreshEnrich } from "@/lib/constants/feature-flags";
import type { IngestionRun } from "@/types/ingestion";
import type { DocumentRunSummary } from "@/types/documents";
import type { Toast } from "@/types/ui";
import { Icon } from "@/components/icons";

type ControlAction =
  | "pause"
  | "cancel"
  | "clean_up"
  | "refresh_enrichment"
  | "run_enrichment";

interface RunControlsProps {
  run: IngestionRun | null;
  /**
   * Server-computed capability flags for THIS run. Coming from the
   * document detail's ``runHistory``. When absent, only the in-flight
   * actions (pause / cancel) are surfaced — destructive and
   * enrichment actions stay hidden until the parent loads it.
   */
  capability?: Pick<
    DocumentRunSummary,
    | "isActive"
    | "isOnlyRun"
    | "canDeleteRun"
    | "canRefreshEnrichment"
    | "canRunEnrichment"
  > | null;
  onRefresh: () => void;
  pushToast: (toast: Omit<Toast, "id">) => void;
  /** Compact list-row variant — narrower buttons, no labels. */
  compact?: boolean;
  /** Invoked after a successful action so the parent can navigate
   *  (e.g. back to the run list after a delete, or to the new
   *  enrichment-refresh run). */
  onAfterAction?: (action: ControlAction, newRunId: string | null) => void;
}

const PAUSE_FROM = PAUSABLE_STATUSES;
const CANCEL_FROM = CANCELLABLE_STATUSES;

export function RunControls({
  run,
  capability = null,
  onRefresh,
  pushToast,
  compact = false,
  onAfterAction,
}: RunControlsProps) {
  const client = useClient();
  const [pending, setPending] = useState<ControlAction | null>(null);

  const dispatch = useCallback(
    async (action: ControlAction) => {
      if (!run || pending) return;
      if (action === "cancel") {
        const ok = window.confirm(
          `Cancel "${run.document_name}"? In-flight stages will wind down; ` +
            `the run will land at CANCELLED.`,
        );
        if (!ok) return;
      }
      if (action === "clean_up") {
        const ok = window.confirm(
          `Clean Up this processing run?\n\n` +
            `This will permanently clean up all data generated by ` +
            `this run — artifacts on disk, chunks, enrichment ` +
            `outputs, validation history, run snapshot, and index ` +
            `records scoped to this run.\n\n` +
            `It will NOT affect the active knowledge run.\n\n` +
            `This cannot be undone.`,
        );
        if (!ok) return;
      }
      setPending(action);
      try {
        let toastTitle = "";
        let toastBody = "";
        let newRunId: string | null = null;
        if (action === "pause" || action === "cancel") {
          let result: RunControlResult;
          if (action === "pause") result = await client.pauseRun(run.runId);
          else result = await client.cancelRun(run.runId);
          const verb = action.charAt(0).toUpperCase() + action.slice(1);
          toastTitle = `${verb} requested`;
          toastBody = result.message ?? `Run is now ${result.status}.`;
        } else if (action === "clean_up") {
          const result = await client.cleanUpRun(run.runId);
          if (!result.cleaned) {
            // Eligibility refusal — surface the server's canonical
            // copy so the UI never re-derives the rules. Not an
            // error (HTTP was 200); the run is intact.
            pushToast({
              kind: "warning",
              title: "Cannot clean up this run",
              body: result.message,
            });
            return;
          }
          toastTitle = "Run cleaned up";
          const c = result.deletedCounts;
          toastBody =
            `${c.workspaceFiles} file(s) + ${c.artifacts} artifact ` +
            `record(s) + ${c.snapshots} run snapshot(s) removed.`;
        } else if (
          action === "refresh_enrichment" || action === "run_enrichment"
        ) {
          const result = await client.refreshRunEnrichment(run.runId);
          toastTitle =
            action === "refresh_enrichment"
              ? "Refresh enrichment started"
              : "Enrichment started";
          toastBody = `New run: ${result.refreshRunId.slice(0, 12)}`;
          newRunId = result.refreshRunId;
        }
        pushToast({ kind: "success", title: toastTitle, body: toastBody });
        if (onAfterAction) onAfterAction(action, newRunId);
      } catch (err) {
        const status = err instanceof ApiError ? err.status : undefined;
        const message =
          err instanceof Error ? err.message : `Failed to ${action} the run.`;
        const verbLabel: Record<ControlAction, string> = {
          pause: "Pause",
          cancel: "Cancel",
          clean_up: "Clean up",
          refresh_enrichment: "Refresh enrichment",
          run_enrichment: "Run enrichment",
        };
        pushToast({
          kind: "error",
          title:
            `${verbLabel[action]} failed` +
            (status != null ? ` (HTTP ${status})` : ""),
          body: message,
        });
      } finally {
        setPending(null);
        onRefresh();
      }
    },
    [client, run, pending, onRefresh, pushToast, onAfterAction],
  );

  if (!run) return null;
  const status = run.status;
  const showPause = PAUSE_FROM.has(status);
  const showCancel = CANCEL_FROM.has(status);
  const canDeleteRun = capability?.canDeleteRun ?? false;
  // Legacy refresh-enrich is hidden when the deployment runs in
  // Manual Actions mode — the user-facing model in that mode is
  // explicit post-index actions (Run Domain Enrichment, Build
  // Knowledge Memory, etc.). The backend endpoint stays available
  // for ops tooling; only the primary FE button is suppressed.
  const canRefreshEnrichment =
    (capability?.canRefreshEnrichment ?? false)
    && !hideLegacyRefreshEnrich;
  const canRunEnrichment = capability?.canRunEnrichment ?? false;
  const isOnlyRun = capability?.isOnlyRun ?? false;
  const isActive = capability?.isActive ?? false;
  const showOnlyRunHint = !compact && isOnlyRun && !isActive;

  const anyButton =
    showPause ||
    showCancel ||
    canDeleteRun ||
    canRefreshEnrichment ||
    canRunEnrichment;

  if (
    !anyButton
    && !showOnlyRunHint
    && status !== RUN_STATUS.CANCELLING
  ) {
    return null;
  }
  if (status === RUN_STATUS.CANCELLING) {
    return (
      <span className="run-controls__cancelling" aria-live="polite">
        <Icon.RefreshCw className="icon-sm spin" /> Cancelling…
      </span>
    );
  }
  const btnClass = compact ? "btn btn--xs" : "btn btn--sm";
  const isPending = (a: ControlAction) => pending === a;
  const anyPending = pending !== null;

  return (
    <div className="run-controls" role="group" aria-label="Run controls">
      {showPause && (
        <button
          type="button"
          className={btnClass}
          disabled={anyPending}
          onClick={() => void dispatch("pause")}
          aria-label="Pause run"
        >
          {isPending("pause") ? (
            <Icon.RefreshCw className="icon-sm spin" />
          ) : (
            <Icon.Pause className="icon-sm" />
          )}
          {!compact && <span style={{ marginLeft: 4 }}>Pause</span>}
        </button>
      )}
      {showCancel && (
        <button
          type="button"
          className={`${btnClass} btn--danger`}
          disabled={anyPending}
          onClick={() => void dispatch("cancel")}
          aria-label="Cancel run"
        >
          {isPending("cancel") ? (
            <Icon.RefreshCw className="icon-sm spin" />
          ) : (
            <Icon.XCircle className="icon-sm" />
          )}
          {!compact && <span style={{ marginLeft: 4 }}>Cancel</span>}
        </button>
      )}
      {canRefreshEnrichment && (
        <button
          type="button"
          className={btnClass}
          disabled={anyPending}
          onClick={() => void dispatch("refresh_enrichment")}
          aria-label="Refresh enrichment for active snapshot"
          title={
            "Build a new candidate snapshot that reuses this run's " +
            "compile output and re-runs enrichment + graph + index. " +
            "Current active knowledge stays live until the new " +
            "candidate is promoted."
          }
          data-testid="run-controls-refresh-enrichment"
        >
          {isPending("refresh_enrichment") ? (
            <Icon.RefreshCw className="icon-sm spin" />
          ) : (
            <Icon.RefreshCw className="icon-sm" />
          )}
          {!compact && (
            <span style={{ marginLeft: 4 }}>
              Refresh enrichment for active snapshot
            </span>
          )}
        </button>
      )}
      {canRunEnrichment && (
        <button
          type="button"
          className={`${btnClass} btn--primary`}
          disabled={anyPending}
          onClick={() => void dispatch("run_enrichment")}
          aria-label="Run enrichment for this run"
          title={
            "Run enrichment on this run for the first time. Re-uses this " +
            "run's compile output."
          }
          data-testid="run-controls-run-enrichment"
        >
          {isPending("run_enrichment") ? (
            <Icon.RefreshCw className="icon-sm spin" />
          ) : (
            <Icon.RefreshCw className="icon-sm" />
          )}
          {!compact && <span style={{ marginLeft: 4 }}>Run enrichment</span>}
        </button>
      )}
      {canDeleteRun && (
        <button
          type="button"
          className={`${btnClass} btn--danger`}
          disabled={anyPending}
          onClick={() => void dispatch("clean_up")}
          aria-label="Clean up this processing run"
          title={
            "Permanently clean up every record this non-active " +
            "processing run owns: artifacts on disk + registry, " +
            "chunks, enrichment outputs, validation history, run " +
            "snapshot, and index records scoped to this run. The " +
            "active knowledge snapshot is never affected — the " +
            "server refuses cleanup of the producing run with a " +
            "clear reason if you try."
          }
          data-testid="run-controls-clean-up"
        >
          {isPending("clean_up") ? (
            <Icon.RefreshCw className="icon-sm spin" />
          ) : (
            <Icon.XCircle className="icon-sm" />
          )}
          {!compact && (
            <span style={{ marginLeft: 4 }}>Clean Up Run</span>
          )}
        </button>
      )}
      {showOnlyRunHint && (
        <p
          className="run-controls__only-run-hint"
          data-testid="run-controls-only-run-hint"
        >
          This is the only run for this document. Use{" "}
          <strong>Remove Knowledge</strong> on the document page to
          delete the document and all related data.
        </p>
      )}
    </div>
  );
}
